# -*- coding: utf-8 -*-
"""Project1_Rule_Based_AI_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULhZhc_rgiFCI4CsYTJuifbSv3Z05Fp3
"""

print("===================================")
print("🤖 Welcome to Rule-Based AI Chatbot")
print("===================================")

name = input("Enter your name: ")
print("Hello", name + "! Nice to meet you.")

print("\nYou can ask me:")
print("- hi")
print("- hello")
print("- how are you")
print("- what is your name")
print("- who created you")
print("- thank you")
print("- bye")

while True:
    message = input("\nYou: ").lower()

    if message in ["hi", "hello", "hey", "hii"]:
      print("Bot: Hello! How can I help you? 😊")

    elif message == "how are you":
        print("Bot: I'm doing great. Thanks for asking!")

    elif message == "what is your name":
        print("Bot: My name is RuleBot.")

    elif message == "who created you":
        print("Bot: I was created by Sakshi as a DecodeLabs Project.")

    elif message == "thank you":
        print("Bot: You're welcome! 😊")

    elif message in ["bye", "exit", "quit", "goodbye"]:
        print("Bot: Goodbye,", name + "! Have a great day! 👋")
        break

    else:
        print("Bot: Sorry, I didn't understand that. Please try another question.")